Refactor/padoride,comment
4T2F/PADO pull request #304
Opened 2024-03-26 08:32 UTC by kmh5038

[🩹 Refactor: Refactor: padoride, comment 뷰에서 사용하는 변수들 뷰모델로 이동]
(https://github.com/4T2F/PADO/commit/1d4ee9931047d79ddca4d627b9386bcaf08f6447)

[🩹 Refactor: padoride 온보딩 리펙토링]
(https://github.com/4T2F/PADO/commit/5eaa06c8ab4f718de04a4d07762e948054467e6b)

2024-03-26 15:23 UTC, Hsungjin approved these changes

2024-03-27 08:00 UTC, ha-nabi approved these changes

2024-03-28 02:11 UTC, Hminchae approved these changes

2024-03-28 02:14 UTC, hamfan524 requested changes
혹시 댓글 쪽 좋아요랑 테스트 해주실 수 있나요?
지금 로직 상 commentViewModel에 다 연결되어서 한개만 좋아요 눌려도 다른 댓글 좋아요도 다 들어올거같은데 확인 부탁드려요

2024-03-28 07:12 UTC, closed without merging